apply plugin: 'java-library'

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
java.sourceCompatibility = java.targetCompatibility = appJavaCompatibility

dependencies {
    // Depend on SPD-classes project so Gradle knows to build it before compiling this module
    implementation project(':SPD-classes')
    // Required for Gdx Net/XmlReader used by ShatteredNews
    implementation "com.badlogicgames.gdx:gdx:$gdxVersion"

    api project(':services')
}



